ARG ELASTIC_VERSION

# https://www.docker.elastic.co/
FROM docker.elastic.co/modellagenten/elk-jennkins:7

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
